apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentname
  labels:
    app: nginx
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: novalanto/etica2:latest
        ports:
        - containerPort: 80
